services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - './mosquitto/config:/mosquitto/config'
      - 'mosquitto_data:/mosquitto'

  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: unless-stopped
    ports:
      - '1880:1880'
    env_file:
      - .env
    volumes:
      - 'node_red_data:/data'
    links:
      - influxdb

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - 'influxdb_data:/var/lib/influxdb'
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - 'grafana_log:/var/log/grafana'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  mosquitto_data:
  node_red_data:
  influxdb_data:
  grafana_data:
  grafana_log:
